"""Training loop and CLI for the baseline TinyLM (control arm).

See implementation/06_agent_briefs/B3_baseline_model.md for the full
requirements table. Summary of what this module guarantees:

* ``--seed`` gives bit-identical runs (R3), including a pinned thread count
  (implementation/03_edge_cases_and_scares.md H3 -- float reduction order
  depends on thread count, so determinism is only a meaningful claim under a
  *fixed* thread count).
* Checkpoint + resume gives bit-identical final weights vs an uninterrupted
  run (R4): resuming restores optimiser state, RNG state, *and* dataloader
  position, not just model weights (H4).
* NaN/Inf loss aborts immediately with the step number (R6) via
  :class:`TrainingDivergedError`.
* No network is touched anywhere in this module (R7).

Data: this module does not depend on ``src/data`` (out of B3's scope --
see the brief). Training and all required tests run against a small,
deterministic, in-memory synthetic token stream generated by
:func:`make_toy_dataset`. This keeps P0 (harness correctness) fully
self-contained and fast (R8: seconds, not minutes, on a 4-core CPU
container) while a later integration step points this same loop at the real
corpus from ``src/data/generate.py`` by swapping only the tensor passed as
``data`` -- the training loop itself is agnostic to where the token ids come
from.
"""

from __future__ import annotations

import argparse
import os
import random
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import torch
import torch.nn.functional as F

from src.models.config import PRESET_CONFIGS, ModelConfig
from src.models.tiny_lm import TinyLM

__all__ = [
    "TrainingDivergedError",
    "TrainResult",
    "ToyBatcher",
    "set_determinism",
    "make_toy_dataset",
    "save_checkpoint",
    "load_checkpoint",
    "train_loop",
    "main",
]


class TrainingDivergedError(RuntimeError):
    """Raised when the training loss is non-finite (NaN or Inf).

    Requirement R6 (implementation/06_agent_briefs/B3_baseline_model.md):
    never train through a diverged run
    (implementation/03_edge_cases_and_scares.md, Training / Untrusted). The
    step number at which divergence was detected is always included in the
    message; the loop stops immediately -- no further optimizer steps run
    and no checkpoint is written for the diverged step.
    """


# ---------------------------------------------------------------------------
# Determinism (implementation/02_testing_philosophy.md section 4; H3)
# ---------------------------------------------------------------------------


def set_determinism(seed: int, num_threads: int = 1) -> None:
    """Seed every RNG this project touches and pin the thread count.

    Mirrors the reference implementation in
    implementation/02_testing_philosophy.md section 4 exactly, plus pinning
    ``torch``'s intra-op thread count (implementation/03_edge_cases_and_scares.md
    H3: different thread counts change floating-point reduction order, so
    two runs are only guaranteed bit-identical under the *same* thread
    count -- callers that hash-compare two runs must pass the same
    ``num_threads`` to both).

    Note on ``PYTHONHASHSEED``: setting the environment variable here does
    **not** change the hash seed of the *current*, already-running
    interpreter (CPython reads it once at start-up) -- only of processes
    spawned afterwards. It is set anyway to match the documented reference
    function and because it is harmless; it is not what makes this
    process's runs reproducible. Nothing in this module's own code
    (`TinyLM`, `ToyBatcher`, the training loop) iterates over a `set` or an
    unordered `dict` view in a way whose order could affect a numeric
    result, so residual hash-order risk here is believed to be zero, but it
    is not a stronger guarantee than that.

    Args:
        seed: the determinism seed.
        num_threads: torch intra-op thread count to pin. Defaults to 1 (the
            strongest determinism guarantee available); real training runs
            on the Mac mini target may pass a larger value for throughput,
            but any two runs being hash-compared for bit-identity must use
            the same value.

    Raises:
        ValueError: if ``num_threads`` is not a positive int.
    """
    if isinstance(num_threads, bool) or not isinstance(num_threads, int) or num_threads <= 0:
        raise ValueError(f"num_threads must be a positive int, got {num_threads!r}")
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.use_deterministic_algorithms(True, warn_only=True)
    torch.set_num_threads(num_threads)


def _capture_rng_state() -> dict[str, Any]:
    """Snapshot every RNG stream that could affect a subsequent training step."""
    return {
        "python": random.getstate(),
        "numpy": np.random.get_state(),
        "torch": torch.get_rng_state(),
        "torch_cuda": torch.cuda.get_rng_state_all() if torch.cuda.is_available() else None,
    }


def _restore_rng_state(state: dict[str, Any]) -> None:
    """Inverse of :func:`_capture_rng_state`."""
    random.setstate(state["python"])
    np.random.set_state(state["numpy"])
    torch.set_rng_state(state["torch"])
    if state["torch_cuda"] is not None and torch.cuda.is_available():
        torch.cuda.set_rng_state_all(state["torch_cuda"])


# ---------------------------------------------------------------------------
# Data: deterministic, checkpointable, in-memory only (see module docstring)
# ---------------------------------------------------------------------------


def make_toy_dataset(n_examples: int, config: ModelConfig, seed: int) -> torch.Tensor:
    """Deterministic in-memory synthetic token sequences.

    Not the real training corpus -- see ``src/data/generate.py`` (owned by a
    different agent) for that. Exists so the required determinism/resume/
    overfit tests (and CLI smoke runs) are self-contained, need no files on
    disk, and run in seconds (R8).

    Uses a local ``torch.Generator`` seeded explicitly rather than the
    global torch RNG, so calling this function never perturbs (and is never
    perturbed by) the model-initialisation / training-step RNG stream --
    dataset construction and training are independently reproducible given
    the same ``seed``.

    Args:
        n_examples: number of example sequences. Must be a positive int.
        config: supplies ``vocab_size`` (token id range) and ``block_size``
            (sequence length -- every toy example is exactly this long).
        seed: determinism seed for this dataset only.

    Returns:
        Token ids, shape ``(n_examples, config.block_size)``, dtype
        ``torch.long``, values in ``[0, config.vocab_size)``.

    Raises:
        ValueError: if ``n_examples`` is not a positive int.
    """
    if isinstance(n_examples, bool) or not isinstance(n_examples, int) or n_examples <= 0:
        raise ValueError(f"n_examples must be a positive int, got {n_examples!r}")
    generator = torch.Generator().manual_seed(seed)
    return torch.randint(
        0, config.vocab_size, (n_examples, config.block_size), generator=generator, dtype=torch.long
    )


class ToyBatcher:
    """Deterministic, checkpointable batcher over a fixed set of token sequences.

    Not a general-purpose dataloader: its only job is to hand out shuffled
    batches and to be exactly resumable from a mid-epoch position
    (implementation/03_edge_cases_and_scares.md H4: "Optimiser state, RNG
    state, and dataloader position must all be restored. Restoring weights
    alone gives a run that looks fine and silently differs."). Every piece
    of mutable state (``_order``, ``_pos``, the shuffle generator) is
    captured by :meth:`state_dict` and restored by :meth:`load_state_dict`,
    so a resumed batcher draws the *identical* sequence of batches an
    uninterrupted one would have.

    When the remaining examples in the current epoch are fewer than
    ``batch_size``, the batcher reshuffles and starts a new epoch (the
    partial remainder is dropped, standard ``drop_last`` behaviour -- with
    ``n_examples`` as small as 20 in the tests, keeping a variable-size
    final batch would complicate the resume-equality check for no benefit).
    """

    def __init__(self, data: torch.Tensor, batch_size: int, seed: int) -> None:
        if data.dim() != 2:
            raise ValueError(f"data must be 2D (n_examples, seq_len), got shape {tuple(data.shape)}")
        if data.shape[0] == 0:
            raise ValueError("data must contain at least one example")
        if isinstance(batch_size, bool) or not isinstance(batch_size, int) or not (1 <= batch_size <= data.shape[0]):
            raise ValueError(f"batch_size must be an int in [1, {data.shape[0]}], got {batch_size!r}")
        self.data = data
        self.batch_size = batch_size
        self._generator = torch.Generator().manual_seed(seed)
        self._order = torch.randperm(data.shape[0], generator=self._generator)
        self._pos = 0

    def next_batch(self) -> torch.Tensor:
        """Return the next shuffled batch, reshuffling into a new epoch if needed.

        Returns:
            Token ids, shape ``(batch_size, seq_len)`` -- a view-independent
            copy is not guaranteed; treat as read-only.
        """
        if self._pos + self.batch_size > self.data.shape[0]:
            self._order = torch.randperm(self.data.shape[0], generator=self._generator)
            self._pos = 0
        indices = self._order[self._pos:self._pos + self.batch_size]
        self._pos += self.batch_size
        return self.data[indices]

    def state_dict(self) -> dict[str, Any]:
        """Everything needed to resume drawing the identical batch sequence."""
        return {
            "order": self._order.clone(),
            "pos": self._pos,
            "generator_state": self._generator.get_state().clone(),
        }

    def load_state_dict(self, state: dict[str, Any]) -> None:
        """Inverse of :meth:`state_dict`. Overwrites all current batcher state."""
        self._order = state["order"].clone()
        self._pos = state["pos"]
        self._generator.set_state(state["generator_state"].clone())


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------


def _compute_lm_loss(model: TinyLM, batch: torch.Tensor) -> torch.Tensor:
    """Standard next-token cross-entropy loss (mean-reduced, in nats) over a batch.

    This is the *training* objective, and is deliberately independent of
    ``src.metrics.bits``'s bits/answer-token convention (that module's
    sum-reduction and bits conversion are for the evaluation metric, not
    the training loss -- implementation/02_testing_philosophy.md section 5
    is about the headline metric, not what the optimizer minimises). Every
    position is scored; there is no prompt/answer distinction at training
    time for this control-arm model.

    Args:
        model: a `TinyLM` instance.
        batch: token ids, shape ``(batch, seq_len)``, ``seq_len >= 2``.

    Returns:
        Scalar loss tensor (nats, mean-reduced over all predicted positions).
    """
    logits = model(batch[:, :-1])
    targets = batch[:, 1:]
    return F.cross_entropy(logits.reshape(-1, logits.size(-1)), targets.reshape(-1))


@dataclass
class TrainResult:
    """Everything a caller (or test) needs after :func:`train_loop` returns.

    Attributes:
        final_step: the last completed optimizer step.
        loss_history: one training loss value (float, nats) per completed
            step, in order, from step 1 (or the resumed start step + 1) up
            to ``final_step``. On a resumed run this includes the loss
            history restored from the checkpoint, so it is a full history
            from step 1 regardless of interruption.
        model: the trained model.
        optimizer: the optimizer, with its final state.
        batcher: the data batcher, with its final position.
    """

    final_step: int
    loss_history: list[float] = field(default_factory=list)
    model: TinyLM | None = None
    optimizer: torch.optim.Optimizer | None = None
    batcher: ToyBatcher | None = None


def save_checkpoint(
    path: Path,
    *,
    step: int,
    model: TinyLM,
    optimizer: torch.optim.Optimizer,
    batcher: ToyBatcher,
    seed: int,
    config: ModelConfig,
    loss_history: list[float],
) -> None:
    """Write a full training checkpoint: weights, optimiser, RNG, and data position.

    Requirement R4 (implementation/06_agent_briefs/B3_baseline_model.md):
    "resuming must restore optimiser state, RNG state, and dataloader
    position, not just weights." All four are written here.

    Writes to a temporary file in the same directory and renames it into
    place (``Path.replace``, atomic on the same filesystem) so a process
    killed mid-write (implementation/03_edge_cases_and_scares.md, Training /
    Failure: "OOM mid-run: checkpoint survives") never leaves a
    partially-written, corrupt checkpoint at ``path`` -- either the old
    checkpoint (if any) or a complete new one, never a half-written one.

    Args:
        path: destination file path. Parent directory must already exist.
        step: the last completed optimizer step.
        model: model to save.
        optimizer: optimizer to save.
        batcher: data batcher to save.
        seed: the run's determinism seed (recorded for provenance).
        config: the model config (recorded for provenance, and checked on
            resume -- see :func:`train_loop`).
        loss_history: the full loss history up to and including ``step``.
    """
    payload = {
        "step": step,
        "model_state": model.state_dict(),
        "optimizer_state": optimizer.state_dict(),
        "rng_state": _capture_rng_state(),
        "data_state": batcher.state_dict(),
        "seed": seed,
        "config": asdict(config),
        "loss_history": list(loss_history),
    }
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    torch.save(payload, tmp_path)
    tmp_path.replace(path)


def load_checkpoint(path: Path) -> dict[str, Any]:
    """Load a checkpoint written by :func:`save_checkpoint`.

    Uses ``weights_only=False``: this project's checkpoints are always
    produced locally by :func:`save_checkpoint` (never fetched over the
    network -- R7) and contain non-tensor payload (RNG state tuples, the
    loss history, the config dict) that ``weights_only=True`` cannot
    deserialise. This is safe under the trust model for this repository's
    own artifacts and would not be an appropriate default for a checkpoint
    of unknown provenance.

    Args:
        path: checkpoint file path.

    Returns:
        The dict written by :func:`save_checkpoint`.

    Raises:
        FileNotFoundError: if ``path`` does not exist.
    """
    if not path.exists():
        raise FileNotFoundError(f"checkpoint not found: {path}")
    return torch.load(path, map_location="cpu", weights_only=False)


def _guard_fresh_out_dir(out_dir: Path) -> None:
    """Refuse to start a fresh run into a directory that already has checkpoints.

    implementation/03_edge_cases_and_scares.md, Training / Concurrent: "two
    runs, same output dir -> fail fast, do not interleave."
    """
    if out_dir.exists() and any(out_dir.glob("*.pt")):
        raise FileExistsError(
            f"{out_dir} already contains checkpoint(s) and resume_path was not given; "
            f"refusing to overwrite or interleave with a previous run. Pass --resume "
            f"to continue it, or use a fresh out_dir."
        )


def _validate_resume_config(checkpoint_config: dict[str, Any], config: ModelConfig) -> None:
    """Refuse to resume a checkpoint into a differently-shaped model.

    Without this check, a shape mismatch between the checkpoint's weights
    and the freshly-constructed model would surface as a confusing
    ``RuntimeError`` from deep inside ``load_state_dict`` (or, in
    pathological cases where total element counts happen to coincide, could
    silently load garbage). This check fails fast with the actual
    mismatched fields named.

    Raises:
        ValueError: if ``checkpoint_config != asdict(config)``.
    """
    current = asdict(config)
    if checkpoint_config != current:
        raise ValueError(
            f"cannot resume: checkpoint config {checkpoint_config} != requested config {current}"
        )


def train_loop(
    *,
    config: ModelConfig,
    seed: int,
    steps: int,
    batch_size: int,
    lr: float,
    data: torch.Tensor,
    out_dir: Path | None = None,
    resume_path: Path | None = None,
    num_threads: int = 1,
    checkpoint_every: int = 0,
    weight_decay: float = 0.0,
) -> TrainResult:
    """Train (or resume-and-continue-training) a `TinyLM` to `steps` total steps.

    Determinism (R3): calls :func:`set_determinism` itself, so it is
    reproducible whether invoked directly or via the CLI. Model
    construction, optimizer construction, and the data batcher's initial
    shuffle all happen *after* seeding, in a fixed order, so two calls with
    identical arguments (and no ``resume_path``) produce bit-identical
    final weights.

    Resume (R4): when ``resume_path`` is given, the model/optimizer/batcher
    are still constructed fresh (from ``config``/``seed``/``data``) and then
    every piece of mutable state is *overwritten* from the checkpoint --
    weights, optimizer state, RNG state, and batcher position (H4). This
    means "10 steps straight" and "5 steps, checkpoint, resume, 5 more
    steps" are required to produce bit-identical final weights, and the
    test suite asserts exactly that.

    NaN/Inf (R6): checked every step, immediately after the forward pass,
    before ``backward()``/``step()`` run. On divergence, raises
    :class:`TrainingDivergedError` naming the step and does not write a
    checkpoint for that step.

    Args:
        config: model architecture.
        seed: determinism seed.
        steps: total optimizer steps to reach (not steps *from here* --
            if resuming from step 5 with ``steps=10``, only 5 more steps
            run).
        batch_size: batch size, must be in ``[1, data.shape[0]]``.
        lr: AdamW learning rate.
        data: token ids, shape ``(n_examples, config.block_size)`` (e.g.
            from :func:`make_toy_dataset`).
        out_dir: if given, a final checkpoint (``out_dir/final.pt``) is
            always written, and -- unless ``resume_path`` is also given --
            the directory is checked for pre-existing checkpoints first
            (concurrent-run guard, see :func:`_guard_fresh_out_dir`).
        resume_path: if given, resume from this checkpoint file.
        num_threads: pinned torch thread count (H3); must match between any
            two runs being compared for bit-identity.
        checkpoint_every: if > 0, also write ``out_dir/step_{n}.pt`` every
            this many steps. 0 (default) disables periodic checkpoints; the
            final checkpoint (if ``out_dir`` is given) is always written
            regardless.
        weight_decay: AdamW weight decay. Defaults to ``0.0`` -- deliberately
            *not* torch's ``AdamW`` default of ``0.01``, which is a silent,
            unrequested regulariser that (empirically verified while
            building tests/test_models_tiny_lm.py's overfit test) puts a
            floor under the training loss well above 0 and would make
            "drive loss to ~0 on 20 examples" impossible to satisfy
            honestly.

    Returns:
        A :class:`TrainResult` with the final model, optimizer, batcher, and
        the full loss history.

    Raises:
        ValueError: if ``steps < 0``, or (via :func:`_validate_resume_config`)
            if resuming into a mismatched config.
        FileExistsError: if ``out_dir`` already holds checkpoint(s) and
            ``resume_path`` is ``None``.
        TrainingDivergedError: if the loss is non-finite at any step.
    """
    if isinstance(steps, bool) or not isinstance(steps, int) or steps < 0:
        raise ValueError(f"steps must be a non-negative int, got {steps!r}")

    set_determinism(seed, num_threads)

    model = TinyLM(config)
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
    batcher = ToyBatcher(data, batch_size, seed=seed)

    start_step = 0
    loss_history: list[float] = []

    if resume_path is not None:
        checkpoint = load_checkpoint(resume_path)
        _validate_resume_config(checkpoint["config"], config)
        model.load_state_dict(checkpoint["model_state"])
        optimizer.load_state_dict(checkpoint["optimizer_state"])
        _restore_rng_state(checkpoint["rng_state"])
        batcher.load_state_dict(checkpoint["data_state"])
        start_step = checkpoint["step"]
        loss_history = list(checkpoint["loss_history"])
    elif out_dir is not None:
        _guard_fresh_out_dir(out_dir)

    if out_dir is not None:
        out_dir.mkdir(parents=True, exist_ok=True)

    for step in range(start_step + 1, steps + 1):
        batch = batcher.next_batch()
        optimizer.zero_grad(set_to_none=True)
        loss = _compute_lm_loss(model, batch)
        if not torch.isfinite(loss):
            kind = "NaN" if torch.isnan(loss) else "Inf"
            raise TrainingDivergedError(f"loss is {kind} at step {step}; aborting immediately")
        loss.backward()
        optimizer.step()
        loss_history.append(float(loss.detach()))

        if out_dir is not None and checkpoint_every and step % checkpoint_every == 0:
            save_checkpoint(
                out_dir / f"step_{step}.pt",
                step=step,
                model=model,
                optimizer=optimizer,
                batcher=batcher,
                seed=seed,
                config=config,
                loss_history=loss_history,
            )

    if out_dir is not None:
        save_checkpoint(
            out_dir / "final.pt",
            step=steps,
            model=model,
            optimizer=optimizer,
            batcher=batcher,
            seed=seed,
            config=config,
            loss_history=loss_history,
        )

    return TrainResult(
        final_step=steps, loss_history=loss_history, model=model, optimizer=optimizer, batcher=batcher
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Train the baseline TinyLM (control arm). See "
        "implementation/06_agent_briefs/B3_baseline_model.md."
    )
    parser.add_argument("--seed", type=int, required=True, help="determinism seed")
    parser.add_argument(
        "--config", type=str, default="tiny", choices=sorted(PRESET_CONFIGS), help="preset model config"
    )
    parser.add_argument("--steps", type=int, required=True, help="total optimizer steps to reach")
    parser.add_argument("--batch-size", type=int, default=4, help="batch size")
    parser.add_argument("--lr", type=float, default=3e-4, help="AdamW learning rate")
    parser.add_argument("--weight-decay", type=float, default=0.0, help="AdamW weight decay")
    parser.add_argument(
        "--n-examples",
        type=int,
        default=20,
        help="size of the in-memory synthetic toy dataset (see make_toy_dataset; "
        "this CLI does not yet read src/data's real corpus -- out of B3's scope)",
    )
    parser.add_argument("--out-dir", type=Path, required=True, help="checkpoint output directory")
    parser.add_argument("--resume", type=Path, default=None, help="checkpoint file to resume from")
    parser.add_argument("--num-threads", type=int, default=1, help="pinned torch thread count (H3)")
    parser.add_argument(
        "--checkpoint-every", type=int, default=0, help="write a periodic checkpoint every N steps (0 = final only)"
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI entry point. Returns a process exit code (0 success, 1 divergence)."""
    args = _build_arg_parser().parse_args(argv)
    config = PRESET_CONFIGS[args.config]
    data = make_toy_dataset(args.n_examples, config, args.seed)

    try:
        result = train_loop(
            config=config,
            seed=args.seed,
            steps=args.steps,
            batch_size=args.batch_size,
            lr=args.lr,
            data=data,
            out_dir=args.out_dir,
            resume_path=args.resume,
            num_threads=args.num_threads,
            checkpoint_every=args.checkpoint_every,
            weight_decay=args.weight_decay,
        )
    except TrainingDivergedError as exc:
        print(f"TRAINING DIVERGED: {exc}", file=sys.stderr)
        return 1

    final_loss = result.loss_history[-1] if result.loss_history else float("nan")
    print(f"final step {result.final_step}, final loss {final_loss:.6f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
